Update Readme
fs/rails-api-format pull request #5
Opened 2016-09-14 21:01 UTC by ruslankhaertdinov

https://github.com/fs/rails_api_format/issues/2

2016-09-14 21:02 UTC, ruslankhaertdinov commented
@timurvafin please take a look

2016-09-15 07:45 UTC, timurvafin requested changes
Could you please add sections about Install, and Usage, Credits?

2016-09-15 08:25 UTC, ruslankhaertdinov commented
Sure, I'll add them later today.

2016-09-20 20:44 UTC, ruslankhaertdinov commented
@timurvafin I remove `Rails API Design` description from Readme, because this gem mostly about error serialization. But was added another requested sections. 
Please take a look when you have a chance.

2016-09-21 09:29 UTC, timurvafin commented
> because this gem mostly about error serialization

– not true. Gem changes response on update, create and delete follows specification of REST API Design. Checkout https://github.com/fs/rails-api-format/blob/master/lib/rails_api_format/responder.rb

2016-09-21 09:32 UTC, ruslankhaertdinov commented
@timurvafin thank you for the clarification, I'll bring back removed part and update readme.

2016-09-21 20:13 UTC, ruslankhaertdinov commented
@timurvafin I updated `Readme` and added link to the [REST API Design](https://github.com/fs/rails-api-format/wiki/REST-API-Design) wiki page

2016-09-22 09:27 UTC, timurvafin commented on README.md
> +`Rails API Format` is maintained by [Timur Vafin](http://github.com/timurvafin).
Let's say `.. is maintained and was written by Flatstack with the help of our contributors.`

2016-09-22 09:28 UTC, timurvafin approved these changes

2016-09-22 09:37 UTC, ruslankhaertdinov commented on README.md
> +`Rails API Format` is maintained by [Timur Vafin](http://github.com/timurvafin).
@timurvafin done

2016-09-22 09:38 UTC, merged